/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: yankobe (https://sketchfab.com/yankobe.do)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-table-set-f487ff6c506842ecb505b47ff3e0b100
Title: Laptop Table Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.016}>
        <group position={[0, -0.321, 59.178]}>
          <primitive object={nodes._rootJoint} />
          <group position={[0, 0.321, -59.178]}>
            <mesh geometry={nodes.P3DA_Base_TableShape_LongTableTop_0.geometry} material={materials.LongTableTop} />
            <mesh geometry={nodes.P3DA_Base_TableShape_LongTableEdge_0.geometry} material={materials.LongTableEdge} />
            <mesh geometry={nodes.P3DA_Base_TableShape_LongTableTopBase_0.geometry} material={materials.LongTableTopBase} />
            <mesh geometry={nodes.P3DA_Base_TableShape_LongTableLegs_0.geometry} material={materials.LongTableLegs} />
            <mesh geometry={nodes.P3DA_Base_TableShape_LongTableLegsEnd_0.geometry} material={materials.LongTableLegsEnd} />
          </group>
          <group position={[0, 0.321, -59.178]}>
            <mesh geometry={nodes.ChairLPShape_Wood_0.geometry} material={materials.Wood} />
            <mesh geometry={nodes.ChairLPShape_Rivets_0.geometry} material={materials.Rivets} />
            <mesh geometry={nodes.ChairLPShape_Frame_0.geometry} material={materials.Frame} />
          </group>
          <group position={[35.829, 78.649, 1.936]} rotation={[-Math.PI, 1.331, -Math.PI]}>
            <mesh geometry={nodes.P3DA_MugShape_Mug_0.geometry} material={materials.material_31} />
            <mesh geometry={nodes.P3DA_MugShape_Contents_0.geometry} material={materials.Contents} />
          </group>
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.LaptopEdge} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.ScreenEdge} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Lens} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Screen} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Laptop} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Rubber} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Brackets} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Badge} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.SideHoles} skeleton={nodes.Object_14.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.USBProng} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Chrome} skeleton={nodes.Object_16.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.LightHD} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.BlackPlastic} skeleton={nodes.Object_18.skeleton} />
          <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.SocketRed} skeleton={nodes.Object_19.skeleton} />
          <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.SocketGreen} skeleton={nodes.Object_20.skeleton} />
          <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.LightDVD} skeleton={nodes.Object_21.skeleton} />
          <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.LightWiFi} skeleton={nodes.Object_22.skeleton} />
          <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.LightBattery} skeleton={nodes.Object_23.skeleton} />
          <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.LightPower} skeleton={nodes.Object_24.skeleton} />
          <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.LaptopPlain} skeleton={nodes.Object_25.skeleton} />
          <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.material} skeleton={nodes.Object_26.skeleton} />
          <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.Button} skeleton={nodes.Object_27.skeleton} />
          <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.Keys} skeleton={nodes.Object_28.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
